config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "posts#index"
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post


  validates :body, presence: true

  def getAuthor
    if user_id.nil?
        return nil
    end

    User.find(user_id).name
  end

  def author?(current_user)
    user_id == current_user.id
  end

end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :user

  has_many :post_tags
  has_many :tags, through: :post_tags

  validates :title, presence: true
  validates :body, presence: true
  validates :user_id, presence: true

  after_save :associate_tags
  before_destroy  :destroy_tags

  def getAuthor
    User.find(user_id).name
  end

  def author?(current_user)
    user_id == current_user.id
  end

  private

  def associate_tags
    # Expressão regular para encontrar todas as tags no corpo do post
    tags = body.scan(/#\w+/)

    tags.each do |tag_name|
      tag = Tag.find_or_create_by(name: tag_name)
      # Associe a tag ao post
      PostTag.find_or_create_by(post_id: id, tag_id: tag.id)
    end
  end

  def destroy_tags
    self.tags.destroy_all
    self.comments.destroy_all
    # Depois essa query pade ser feita no sidekiq
    Tag.left_outer_joins(:post_tags).where(post_tags: { id: nil }).destroy_all
  end

end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags
  has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:name]

  # Incluir nome no nosso usuário
  validates :name, presence: true , uniqueness: true
  has_many :posts, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # Adicionar o parametro name aos do User
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to root_path
  end

  def destroy
    @post = Post.find(params[:post_id])
    authorize_user_modify

    @comment = @post.comments.find(params[:id])

    if @comment.destroy
      flash[:success] = 'Object was successfully deleted.'
    else
      flash[:error] = 'Something went wrong'
    end

    redirect_to root_path
  end


  private
    def comment_params
      params.require(:comment).permit(:user_id, :body)
    end

    def authorize_user_modify
      # O dono do post pode deletar comentários anonimos
      unless user_signed_in? and current_user.id == @post.user_id
        redirect_to root_path, alert: 'Você não tem permissão para acessar esta página.'
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # Procurar um jeito melhor de authenticar e bloquear áreas
  before_action :set_post, only: [:edit, :update, :destroy]
  before_action :authorize_user_modify, only: [:edit, :update, :destroy]
  before_action :authorize_user, only: [:new]

  def index
    @posts = Post.order(created_at: :desc).paginate(page: params[:page], per_page: 3)

    if !params[:tag_id].nil?
      @posts = @posts.joins(:post_tags).where(post_tags: { tag_id: params[:tag_id] })
    end
  end


  def show
    @post = Post.find(params[:id])
  end

  def new
    @post= Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = "Object successfully created"
      redirect_to posts_url
    else
      flash[:alert] = "Something went wrong"
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      flash[:success] = 'Object was successfully deleted.'
    else
      flash[:alert] = 'Something went wrong'
    end

    redirect_to posts_url
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
      if @post.update(post_params)
        flash[:success] = "Object was successfully updated"
        redirect_to posts_url
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def authorize_user
    unless user_signed_in?
      redirect_to root_path, alert: 'Você não tem permissão para acessar esta página.'
    end
  end

  def authorize_user_modify
    # Verifique se o usuário atual é o autor do post
    unless user_signed_in? and current_user.id == @post.user_id
      redirect_to root_path, alert: 'Você não tem permissão para acessar esta página.'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<% if post.comments.size > 0%>
    <div class="comment-container mt-5">
        <p><b>Comentários:</b></p>
        <% post.comments.each do |comment|%>

            <div class="card mb-1">
                <div class="card-body p-2">

                    <% if comment.getAuthor.nil?%>
                        <p class="card-text" style="font-size:16px"><b>Anônimo:</b> <%=comment.body%></p>
                    <%else%>
                        <p class="card-text" style="font-size:16px"><b><%=comment.getAuthor%></b>: <%=comment.body%></p>
                    <%end%>

                    <% if user_signed_in? and (comment.author?(current_user) or (post.author?(current_user) and comment.getAuthor.nil?)  )%>
                        <%= link_to "Excluir", post_comment_path(comment.post, comment), 
                            class: "btn btn-danger float-right p-1",
                            data: { 
                                turbo_method: :delete, 
                                turbo_confirm: "Tem certeza que deseja deletar esse Comentário?" 
                            } 
                        %>
                    <% end %>
                    
                </div>
            </div>
        <%end%>
    </div>

<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [post, post.comments.build] do |form| %>
    <div class="input-group mt-5">
        <%= form.text_area :body, class: "form-control", placeholder: "Escreva um commentário", rows: "1" %>
        
        <%if user_signed_in?%>
            <%= form.hidden_field :user_id, value: current_user.id%>
        <% end %>
        
        <div class="input-group-append">
            <%= form.submit "Enviar", class: "btn btn-outline-secondary"%>
        </div>

    </div>
<%end%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="font-size: 20px;">
    <a class="navbar-brand" href="/">Mainô Blog</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item active ">
                <a class="nav-link" href="/">Página principal</a>
            </li>


            <% if user_signed_in? %>

                <li class="nav-item active">
                    <%= link_to "Novo Post", new_post_path, class: "nav-link" %>
                </li>

                <li class="nav-item dropdown active">

                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Olá! <%=current_user.name%>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <%= link_to "Editar conta", "/users/edit", class: "dropdown-item"%>
                        <%= link_to 'Logout', destroy_user_session_path, data: { "turbo-method": :delete }, class: "dropdown-item" %>
                    </div>

                </li>

            <% else %>
                <li class="nav-item active">
                    <%= link_to 'Login', new_user_session_path, class: "nav-link"  %>
                </li>
            <% end %>


        </ul>

    </div>
</nav>

<div class="avisos mt-1 mb-5">
    <% if !notice.nil?%>
        <p class="alert alert-success"><%= notice %></p>
    <% end %>

    <% if !alert.nil?%>
        <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MainoBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <%= yield %>
  </body>
</html>

app/views/posts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item active">
                <a class="nav-link" href="/posts/new">New post</a>
            </li>
            
            <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
            </li>
            
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown link
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>

            <li class="nav-item active">
                <% if user_signed_in? %>
                    <%= link_to 'Logout', destroy_user_session_path, data: { "turbo-method": :delete }, class: "nav-link" %>
                <% else %>
                    <%= link_to 'Login', new_user_session_path, class: "nav-link"  %>
                <% end %>
            </li>

            <li class="nav-item active">
                <% if user_signed_in? %>
                    <a class="nav-link" >Olá! <%=current_user.name%></a>
                <% end %>
            </li>

        </ul>

    </div>

</nav>

app/views/posts/edit.html.erb
<div class="card p-4 m-4 mx-auto" style="width: 40%;">
    <h2 class="mx-auto mb-3">Edite seu Post</h2>

    <%= form_with(model: @post, url: post_path(@post), method: :patch) do |form| %>

        <div class="form-group mb-4">
            <label>Titulo:</label>
            <%= form.text_field :title, class: "form-control", value: @post.title%>
        </div>

        <div class="form-group mb-4">
            <label>Texto:</label>
            <%= form.text_area :body, class: "form-control", rows: "3", value: @post.body%>
        </div>

        <%= form.hidden_field :user_id, value: current_user.id %>

        <%= form.submit "Atualizar Post", class: "btn btn-primary" %>
        <%= link_to 'Back', posts_path %>

    <% end %>
</div>

app/views/posts/index.html.erb
<div class="mx-auto" style="margin-top: 50px;">

<% if @posts.size < 1 %>

    <div class="card mb-4 mx-auto" style="width: 70%;">
        <div class="card-header">
            <h2>Nenhum post foi feito ainda</h2>
        </div>

        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <% if user_signed_in? %>
                    <p>Faça um post na aba Novo post ou no botão abaixo se estiver logado</p>
                <% else %>
                    <p>Crie uma conta e faça o primeiro post</p>
                <% end %>
                
                <footer class="blockquote-footer">
                    <cite title="Source Title">Mainô Dev</cite>
                    <% if user_signed_in?%>
                        <%= link_to "Novo Post", new_post_path, 
                            class: "btn btn-success float-right"
                        %>
                    <%end%>
                </footer>

            </blockquote>
        </div>
    </div>

    
<% else %>

    <%= form_tag posts_path, method: :get, class: "form-group mx-auto", style: "width: 70%"  do %>
        <%= select_tag :tag_id, options_for_select(Tag.pluck(:name, :id), params[:tag_id]), multiple: true, class: "form-control", prompt: "Selecione as tags..." %>
        <%= submit_tag "Filtrar", class: "btn btn-primary" %>
    <% end %>

    <% @posts.each do |post| %>
            <div class="card mb-4 mx-auto" style="width: 70%;">
                <%=link_to post, style: "text-decoration: none; color: inherit;" do %>
                    <div class="card-header">
                        <h2><%=post.title%></h2>
                    </div>
                <%end%>
                <div class="card-body">
                    <blockquote class="blockquote mb-0">
                        <p><%=post.body%></p>
                        <footer class="blockquote-footer">
                            <cite title="Source Title"><%=post.getAuthor%></cite>

                            <% if user_signed_in? and post.author?(current_user) %>
                                <%= link_to "Excluir", post, 
                                    class: "btn btn-danger float-right",
                                    data: { 
                                        turbo_method: :delete, 
                                        turbo_confirm: "Tem certeza que deseja deletar esse Post?" 
                                    } 
                                %>

                                <%= link_to "Editar", edit_post_path(post), 
                                    class: "btn btn-warning float-right"
                                %>
                            <%end%>
                        </footer>
                         
                        <%= render "comments/comment", post: post%>
                        <%= render "comments/form", post: post%>

                    </blockquote>
                </div>
            </div>

    <% end %>

<% end %>


</div>


<div class="apple_pagination">
  <%= will_paginate @posts, previous_label: "«", next_label: "»", inner_window: 1, outer_window: 1, :container => false %>
</div>

app/views/posts/new.html.erb
<div class="card p-4 m-4 mx-auto" style="width: 40%;">
    <h2 class="mx-auto mb-3">Novo Post</h2>

    <%= form_with(model: @post, url: posts_path ) do |form| %>

        <div class="form-group mb-4">
            <label>Titulo:</label>
            <%= form.text_field :title, class: "form-control"%>
        </div>

        <div class="form-group mb-4">
            <label>Texto:</label>
            <%= form.text_area :body, class: "form-control", rows: "3"%>
        </div>

        <%= form.hidden_field :user_id, value: current_user.id %>

        <%= form.submit "Criar Post", class: "btn btn-primary" %>
        <%= link_to 'Back', posts_path %>

    <% end %>
</div>

app/views/posts/show.html.erb
<div class="card mb-4 mx-auto" style="width: 70%;">
    <div class="card-header">
        <h2><%=@post.title%></h2>
    </div>
    <div class="card-body">
        <blockquote class="blockquote mb-0">
            <p><%=@post.body%></p>
            <footer class="blockquote-footer">
                <cite title="Source Title"><%=@post.getAuthor%></cite>

                <% if user_signed_in? and @post.author?(current_user)%>
                    <%= link_to "Excluir", @post, 
                        class: "btn btn-danger float-right",
                        data: { 
                            turbo_method: :delete, 
                            turbo_confirm: "Tem certeza que deseja deletar esse Post?" 
                        } 
                    %>

                    <%= link_to "Editar", edit_post_path(@post), 
                        class: "btn btn-warning float-right"
                    %>
                <%end%>
            </footer>
            <%= render "comments/comment", post: @post%>
            <%= render "comments/form", post: @post%>
        </blockquote>
    </div>
</div>